spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 169837248065-rb1gfdue2k3uh2irg1bqlcm32slh634i.apps.googleusercontent.com
            clientSecret: ripGOPPQhzCQFbxuWpDHVscg


server:
  port: 8080


