spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 169837248065-rb1gfdue2k3uh2irg1bqlcm32slh634i.apps.googleusercontent.com
            client-secret: ripGOPPQhzCQFbxuWpDHVscg
            scope:
              - email
              - profile
server:
  port: 8080


